### ISSUE TITLE
FT on liveserver url raises AttributeError

### ISSUE THREAD

**Issue by berghaus** [berghaus/superlists#1]
Running the FT on a live server URL causes the following error to show up:

```
======================================================================
ERROR: tearDownClass (functional_tests.tests.NewVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/berghaus/Documents/tdd/superlists/functional_tests/tests.py", line 21, in tearDownClass
    if cls.server_url == cls.live_server_url:
  File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 193, in __get__
    return self.fget(owner)
  File "/usr/local/lib/python3.5/site-packages/django/test/testcases.py", line 1306, in live_server_url
    cls.server_thread.host, cls.server_thread.port)
AttributeError: type object 'NewVisitorTest' has no attribute 'server_thread'
```

What gives?

**Comment by berghaus** [comment]
Looks like the live_server_url only gets created when StaticLiveServerTestCase's setUpClass is called. But this does not happen if the code finds an argument:

``` python
    @classmethod
    def setUpClass(cls):
        for arg in sys.argv:
            if 'liveserver' in arg:
                cls.server_url = 'http://' + arg.split('=')[1]
                return
        super().setUpClass()
        cls.server_url = cls.live_server_url
```

So it seemed like the simplest fix is to give the cls a live_server_url that is notably different from the server_url, such that the tearDownClass still works as intended:

``` python
    @classmethod
    def tearDownClass(cls):
        if cls.server_url == cls.live_server_url:
            super().tearDownClass()
```

**Comment by berghaus** [comment]
Fixed in 5581813 by setting live_server_url to an empty string in setUpClass when a liveserver is found in the arguments.

**Comment by sangmoon** [comment]
Good fix! I had the same problem, and didn't know what to do.
Thank you for your bright solution!

**Comment by imhuwq** [comment]
Awesome!

**Comment by apple-blossom** [comment]
Wow. 30 minutes of googling and that's the only right answer. Thank you!

**Comment by thiagolcmelo** [comment]
Thank you! Awesome!
